name: base
channels:
  - defaults
dependencies:
  - pip=21.0.1
  - python=3.9
  - conda-forge::elastic
  - conda-forge::lammps
  - openmpi
  - mpi4py
  - pip:
      - spglib
      - ase == 3.22.1
      - matgl == 0.9.1
      - seaborn
      - SciencePlots
      - torch
      - torchvision
      - torchaudio
      - mace-torch == 0.3.3
      - chgnet == 0.3.1
      - alignn
      - deepmd-kit[cpu]==2.2.7
variables:
  ASE_LAMMPSRUN_COMMAND: "lmp_serial"
